openapi: 3.0.3

info:
  title: Dossier Simpson Services API
  description: An API for managing and viewing personal documents
  version: 1.0.0

servers:
  - url: https://dossier.simpson.services/api
    description: The primary server where the api will be served
  - url: https://dossier-test.simpson.services/api
    description: The test server where the api will be served
  - url: http://localhost:9080/api
    description: The local open liberty server wehre the api will be served

paths:
  /document:
    get:
      operationId: listDocuments
      description: Returns document references for all documents the caller is permitted to list
      responses:
        200:
          description: A list of document references.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DocumentReference'
    post:
      operationId: uploadDocument
      description: Uploads a document
      requestBody:
        description: A json containing a base64 encoded document
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentUpload'
      responses:
        200:
          description: A document reference.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentReference'
  /document/{documentId}:
    get:
      operationId: readDocument
      description: Returns content of a specific document identified by the documentId
      parameters:
        - name: documentId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/DocumentId'
      responses:
        200:
          description: A base64 encoded document
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'

components:
  schemas:
    DocumentId:
      type: string
      format: uuid
    Document:
      type: object
      properties:
        content:
          type: string
          format: byte
      required:
        - content
    DocumentReference:
      type: object
      properties:
        id:
          type: string
          format: uuid
        lastModified:
          type: number
        mimeType:
          type: string
        name:
          type: string
      # Both properties are required
      required:
        - id
        - lastModified
        - mimeType
        - name
    DocumentUpload:
      type: object
      properties:
        document:
          $ref: '#/components/schemas/Document'
        documentReference:
          $ref: '#/components/schemas/DocumentReference'
