name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven and Sonar
        run: mvn --batch-mode --update-snapshots package sonar:sonar -Dsonar.token=${{ secrets.SONAR_BENSIMPSON_CH }} -sonar.host.url=https://sonar.bensimpson.ch
